# Generated by Django 5.2.6 on 2025-09-26 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('STANDARD', 'Стандартный'), ('PREMIUM', 'Премиум'), ('VIP', 'VIP')], max_length=20, verbose_name='Тип абонемента')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('duration_days', models.IntegerField(verbose_name='Срок действия (дни)')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО тренера')),
                ('specialization', models.CharField(choices=[('YOGA', 'Йога'), ('CARDIO', 'Кардио'), ('STRENGTH', 'Силовые тренировки'), ('CROSSFIT', 'Кроссфит')], max_length=20, verbose_name='Специализация')),
                ('work_schedule', models.TextField(verbose_name='График работы')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название занятия')),
                ('duration', models.IntegerField(verbose_name='Длительность (минуты)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('time', models.DateTimeField(verbose_name='Время проведения')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО клиента')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.membership', verbose_name='Абонемент')),
                ('workouts', models.ManyToManyField(to='fitness.workout', verbose_name='Занятия')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
