# Generated by Django 5.2.6 on 2025-09-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
